# Projeto de Python para Finanças

In [252]:
# instalação
# pip install yfinance pandas numpy plotly nbformat

### Parte 1: Obter cotações e construção de carteira

In [253]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta 

acoes = ["ITUB4.SA", "PETR4.SA","VALE3.SA","IVVB11.SA"]
# IBOVESPA = "^BVSP"
# S&P500 = "^GSPC"
# Dólar = "BRL=X"
# Ouro = "GC=F"

indices = ["^BVSP","^GSPC","BRL=X","GC=F"]

data_incio = datetime.now() - timedelta(days=730)
data_incio = data_incio.strftime("%Y-%m-%d")
data_fim = datetime.now().strftime("%Y-%m-%d")
print(data_fim, data_incio)

def pegar_cotacoes(listas_tickers, data_incio, data_fim):
    df = yf.download(listas_tickers,data_incio,data_fim, auto_adjust=False)
    df = df["Adj Close"]
    df = df.ffill()
    df = df.dropna()
    return df
lista_cotacoes = acoes + indices
df_cotacoes = pegar_cotacoes(lista_cotacoes, data_incio, data_fim)
display(df_cotacoes)

[                       0%                       ]

2026-07-03 2024-07-03

[*********************100%***********************]  8 of 8 completed

Ticker,BRL=X,GC=F,ITUB4.SA,IVVB11.SA,PETR4.SA,VALE3.SA,^BVSP,^GSPC
Date,,,,,,,,
2024-07-03,5.675500,2359.800049,24.549572,342.000000,29.680302,54.224037,125662.0,5537.020020
2024-07-04,5.555400,2359.800049,24.586924,337.920013,29.272432,53.953674,126164.0,5537.020020
2024-07-05,5.486400,2388.500000,24.601858,338.510010,29.429304,53.734013,126267.0,5567.189941
2024-07-08,5.471290,2355.199951,24.557034,339.670013,30.150919,53.311573,126548.0,5572.850098
2024-07-09,5.470400,2360.100098,24.728870,336.220001,30.143072,53.243980,127108.0,5576.979980
...,...,...,...,...,...,...,...,...
2026-06-29,5.170700,4022.300049,42.391720,433.399994,38.139999,78.129997,173205.0,7440.430176
2026-06-30,5.181787,4022.899902,42.161819,435.649994,37.799999,77.879997,172024.0,7499.359863
2026-07-01,5.174700,4068.300049,42.439999,439.200012,37.830002,77.970001,171689.0,7483.229980
2026-07-02,5.220600,4112.700195,42.470001,439.000000,37.959999,78.239998,172788.0,7483.240234
2026-07-03,5.222200,4112.700195,42.470001,439.000000,37.959999,78.239998,172788.0,7483.240234

In [254]:
# CARTEIRA EM TERMOS DE VALOR FINANCEIRO
dic_carteira = {
    "ITUB4.SA": 5000,
    "PETR4.SA": 4000,
    "VALE3.SA": 3000,
    "IVVB11.SA": 6000
}

df_carteira = pd.DataFrame()
total_investido = sum(dic_carteira.values())
print(total_investido)

for ativo in dic_carteira:
    preco_inicial_ativo = df_cotacoes[ativo].iloc[0]
    qtde_acoes = dic_carteira[ativo] / preco_inicial_ativo
    df_carteira[ativo] = df_cotacoes[ativo] * qtde_acoes
df_carteira["Total"] = df_carteira.sum(axis=1)
display(df_carteira)

18000

               ITUB4.SA     PETR4.SA     VALE3.SA    IVVB11.SA         Total
Date
2024-07-03  5000.000000  4000.000000  3000.000000  6000.000000  18000.000000
2024-07-04  5007.607385  3945.031645  2985.041900  5928.421288  17866.102218
2024-07-05  5010.649096  3966.173182  2972.888893  5938.772101  17888.483271
2024-07-08  5001.519690  4063.424867  2949.516993  5959.123043  17973.584593
2024-07-09  5036.517623  4062.367353  2945.777363  5898.596513  17943.258851
...                 ...          ...          ...          ...           ...
2026-06-29  8633.902015  5140.109399  4322.621553  7603.508665  25700.141632
2026-06-30  8587.078315  5094.287742  4308.790049  7642.982349  25633.138455
2026-07-01  8643.734938  5098.331177  4313.769610  7705.263372  25761.099097
2026-07-02  8649.845553  5115.850844  4328.707449  7701.754386  25796.158231
2026-07-03  8649.845553  5115.850844  4328.707449  7701.754386  25796.158231

[519 rows x 5 columns]

### Parte 2: Rentabilidade e Comparação com Benchmarks

In [255]:
df_cotacoes["SP500 (R$)"] = df_cotacoes["^GSPC"] * df_cotacoes["BRL=X"]
df_cotacoes["ouro (R$)"] = df_cotacoes["GC=F"] * df_cotacoes["BRL=X"]
df_cotacoes["Dólar"] = df_cotacoes["BRL=X"]

df_cotacoes = df_cotacoes.drop(columns=["^GSPC","GC=F","BRL=X"])
display(df_cotacoes)

Ticker,ITUB4.SA,IVVB11.SA,PETR4.SA,VALE3.SA,^BVSP,SP500 (R$),ouro (R$),Dólar
Date,,,,,,,,
2024-07-03,24.549572,342.000000,29.680302,54.224037,125662.0,31425.356656,13393.044979,5.675500
2024-07-04,24.586924,337.920013,29.272432,53.953674,126164.0,30760.360434,13109.632943,5.555400
2024-07-05,24.601858,338.510010,29.429304,53.734013,126267.0,30543.831604,13104.266704,5.486400
2024-07-08,24.557034,339.670013,30.150919,53.311573,126548.0,30490.679632,12885.982204,5.471290
2024-07-09,24.728870,336.220001,30.143072,53.243980,127108.0,30508.310485,12910.691236,5.470400
...,...,...,...,...,...,...,...,...
2026-06-29,42.391720,433.399994,38.139999,78.129997,173205.0,38472.232855,20798.107157,5.170700
2026-06-30,42.161819,435.649994,37.799999,77.879997,172024.0,38860.085553,20845.810473,5.181787
2026-07-01,42.439999,439.200012,37.830002,77.970001,171689.0,38723.468559,21052.231381,5.174700
2026-07-02,42.470001,439.000000,37.959999,78.239998,172788.0,39067.004927,21470.763167,5.220600
2026-07-03,42.470001,439.000000,37.959999,78.239998,172788.0,39078.976530,21477.342618,5.222200

In [256]:
#valor_final = 18102
#valor_inicial = 18000
#variacao_reais = valor_final - valor_inicial
#variacao_percentual = (variacao_reais / valor_inicial) * 100
#print(f"Variação em reais: {variacao_reais:.2f}")
#print(f"Variação percentual: {variacao_percentual:.2f}%")

def calcular_retorno(df):
    retorno = df.iloc[-1] / df.iloc[0] -1
    return retorno
display(calcular_retorno(df_carteira))
display(calcular_retorno(df_cotacoes))

ITUB4.SA     0.729969
PETR4.SA     0.278963
VALE3.SA     0.442902
IVVB11.SA    0.283626
Total        0.433120
dtype: float64

Ticker
ITUB4.SA      0.729969
IVVB11.SA     0.283626
PETR4.SA      0.278963
VALE3.SA      0.442902
^BVSP         0.375022
SP500 (R$)    0.243549
ouro (R$)     0.603619
Dólar        -0.079870
dtype: float64

In [257]:
df_comparacao = df_cotacoes.drop(columns=acoes)
df_comparacao["carteira"] = df_carteira["Total"]
display(df_comparacao)
print(calcular_retorno(df_comparacao))

Ticker         ^BVSP    SP500 (R$)     ouro (R$)     Dólar      carteira
Date
2024-07-03  125662.0  31425.356656  13393.044979  5.675500  18000.000000
2024-07-04  126164.0  30760.360434  13109.632943  5.555400  17866.102218
2024-07-05  126267.0  30543.831604  13104.266704  5.486400  17888.483271
2024-07-08  126548.0  30490.679632  12885.982204  5.471290  17973.584593
2024-07-09  127108.0  30508.310485  12910.691236  5.470400  17943.258851
...              ...           ...           ...       ...           ...
2026-06-29  173205.0  38472.232855  20798.107157  5.170700  25700.141632
2026-06-30  172024.0  38860.085553  20845.810473  5.181787  25633.138455
2026-07-01  171689.0  38723.468559  21052.231381  5.174700  25761.099097
2026-07-02  172788.0  39067.004927  21470.763167  5.220600  25796.158231
2026-07-03  172788.0  39078.976530  21477.342618  5.222200  25796.158231

[519 rows x 5 columns]

Ticker
^BVSP         0.375022
SP500 (R$)    0.243549
ouro (R$)     0.603619
Dólar        -0.079870
carteira      0.433120
dtype: float64

In [258]:
df_comparacao = (df_comparacao / df_comparacao.iloc[0] -1)*100
display(df_comparacao)

import plotly.express as px
grafico = px.line(df_comparacao, x=df_comparacao.index, y=df_comparacao.columns)
grafico.update_layout(template="plotly_dark")
grafico.show()

Ticker          ^BVSP  SP500 (R$)  ouro (R$)     Dólar   carteira
Date
2024-07-03   0.000000    0.000000   0.000000  0.000000   0.000000
2024-07-04   0.399484   -2.116114  -2.116114 -2.116114  -0.743877
2024-07-05   0.481450   -2.805139  -2.156181 -3.331861  -0.619537
2024-07-08   0.705066   -2.974277  -3.786016 -3.598094  -0.146752
2024-07-09   1.150706   -2.918173  -3.601524 -3.613780  -0.315229
...               ...         ...        ...       ...        ...
2026-06-29  37.834031   22.424173  55.290355 -8.894368  42.778565
2026-06-30  36.894208   23.658376  55.646535 -8.699021  42.406325
2026-07-01  36.627620   23.223641  57.187790 -8.823895  43.117217
2026-07-02  37.502188   24.316823  60.312783 -8.015149  43.311990
2026-07-03  37.502188   24.354918  60.361909 -7.986962  43.311990

[519 rows x 5 columns]

### Parte 3: Análise de Risco

In [259]:
import numpy as np
# correlação
df_cotacoes["carteira"] = df_carteira["Total"]

#rentabilidade diária
tabela_rentabilidade_diaria = df_cotacoes / df_cotacoes.shift(1)
tabela_rentabilidade_diaria = np.log(tabela_rentabilidade_diaria).dropna()
tabela_correlacao = tabela_rentabilidade_diaria.corr()


grafico_correlacao = px.imshow(tabela_correlacao, text_auto=True, color_continuous_scale="greens")
grafico_correlacao.update_layout(template="plotly_dark")
grafico_correlacao.show()

# variância
display(tabela_rentabilidade_diaria)
tabela_volatilidade = tabela_rentabilidade_diaria.std() * np.sqrt(252)
display(tabela_volatilidade)

Ticker,ITUB4.SA,IVVB11.SA,PETR4.SA,VALE3.SA,^BVSP,SP500 (R$),ouro (R$),Dólar,carteira
Date,,,,,,,,,
2024-07-04,0.001520,-0.012002,-0.013837,-0.004999,0.003987,-0.021388,-0.021388,-0.021388,-0.007467
2024-07-05,0.000607,0.001744,0.005345,-0.004080,0.000816,-0.007064,-0.000409,-0.012498,0.001252
2024-07-08,-0.001824,0.003421,0.024224,-0.007893,0.002223,-0.001742,-0.016798,-0.002758,0.004746
2024-07-09,0.006973,-0.010209,-0.000260,-0.001269,0.004415,0.000578,0.001916,-0.000163,-0.001689
2024-07-10,0.010518,0.010150,-0.009412,-0.013580,0.000865,0.000365,-0.004677,-0.009791,0.001985
...,...,...,...,...,...,...,...,...,...
2026-06-29,0.004017,0.014807,0.002100,-0.000256,-0.000519,0.007166,-0.018440,-0.004515,0.006090
2026-06-30,-0.005438,0.005178,-0.008955,-0.003205,-0.006842,0.010031,0.002291,0.002142,-0.002611
2026-07-01,0.006576,0.008116,0.000793,0.001155,-0.001949,-0.003522,0.009854,-0.001369,0.004980
2026-07-02,0.000707,-0.000456,0.003430,0.003457,0.006381,0.008832,0.019686,0.008831,0.001360
2026-07-03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000306,0.000306,0.000306,0.000000

Ticker
ITUB4.SA      0.213234
IVVB11.SA     0.155779
PETR4.SA      0.238215
VALE3.SA      0.247595
^BVSP         0.156144
SP500 (R$)    0.217290
ouro (R$)     0.262087
Dólar         0.131870
carteira      0.117452
dtype: float64

### Parte 4: Análise Técnica e Indicadores

In [265]:
ticker = "VALE3.SA"
import yfinance as yf
import plotly.graph_objects as go

df = yf.download(ticker,"2020-01-01","2025-12-31",multi_level_index=False)  
display(df)
#média movel de 50 dias
df["MM50"] = df["Close"].rolling(50).mean()

#Média móvel de 200 dias
df["MM200"] = df["Close"].rolling(200).mean()


grafico = go.Figure()
grafico.add_trace(go.Candlestick(x=df.index,open=df["Open"], high=df["High"], low=df["Low"], close=df["Close"]))
#adicionando médias móveis
grafico.add_trace(go.Scatter(x=df.index, y=df["MM50"], mode="   lines", name="MM50", line=dict(color="blue", width=1)))
grafico.add_trace(go.Scatter(x=df.index, y=df["MM200"], mode="lines", name="MM200", line=dict(color="yellow", width=1)))


grafico.update_layout(template="plotly_dark")
grafico.show()

[*********************100%***********************]  1 of 1 completed

                Close       High        Low       Open    Volume
Date
2020-01-02  30.140163  30.201185  29.818401  29.945996  17509700
2020-01-03  29.918255  30.234468  29.724089  29.779565  17284800
2020-01-06  29.740728  29.846132  29.485539  29.846132  32787800
2020-01-07  29.957092  30.062496  29.624237  29.679712  16326400
2020-01-08  29.962633  30.162347  29.746277  30.068039  15298500
...               ...        ...        ...        ...       ...
2025-12-22  72.919998  73.370003  70.809998  71.029999  27853000
2025-12-23  72.900002  73.529999  72.580002  73.230003  17140900
2025-12-26  73.120003  73.349998  72.620003  72.860001  16368800
2025-12-29  72.120003  73.739998  71.699997  73.190002  19963700
2025-12-30  71.959999  72.839996  71.910004  72.500000  17085400

[1494 rows x 5 columns]